name: flokk
description: A fresh and modern Google Contacts manager that integrates with GitHub and Twitter.
version: 1.0.1
environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animations: ^1.0.0+5
  cupertino_icons: ^0.1.3
  time: ^1.3.0
  dotted_border: ^1.0.5
  draggable_scrollbar: ^0.0.4
  faker: ^1.2.1
  flutter_hooks: ^0.8.0
  #flutter_svg: ^0.18.0 # removed due to issues with Web builds
  github: ^6.1.3
  google_sign_in: ^4.1.4
  googleapis: ^0.54.0
  http: ^0.12.0+4
  image: ^2.1.12
  intl: ^0.16.1
  json_annotation: ^3.0.0
  package_info: ^0.4.0+13
  path: ^1.6.4
  path_provider: 1.6.1
  path_provider_macos: ^0.0.4
  provider: ^4.1.0-dev+2
  rnd: ^0.1.0
  shared_preferences:
  sized_context: ^0.2.1
  statsfl: ^0.0.3
  styled_widget:
    git:
      url: git://github.com/gskinnerTeam/styled_widget.git
  textstyle_extensions: ^1.0.0
  timeago: ^2.0.26
  tuple: ^1.0.3
  universal_platform: ^0.1.2
  url_launcher:
  xdg_directories: ^0.1.0

  file_chooser:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/file_chooser
      ref: dc5bad31ae93dd5d82e235e38d5c21b6a47445ab
  path_provider_fde:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/flutter_plugins/path_provider_fde
      ref: dc5bad31ae93dd5d82e235e38d5c21b6a47445ab
  window_size:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: dc5bad31ae93dd5d82e235e38d5c21b6a47445ab

dev_dependencies:
  json_serializable: ^3.2.0 # Generate JSON parsers: flutter pub run build_runner build --delete-conflicting-outputs

flutter:
  uses-material-design: true
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Light.ttf
          weight: 200
        - asset: assets/fonts/Quicksand-Regular.ttf
          weight: 400
        - asset: assets/fonts/Quicksand-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 600
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700

    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Thin.ttf
          weight: 200
        - asset: assets/fonts/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato-Black.ttf
          weight: 800

    - family: OpenSansEmoji
      fonts:
        - asset: assets/fonts/OpenSansEmoji.ttf

  assets:
    - assets/images/
    - assets/images/birds/
    - assets/images/flokk-logo.svg
    - assets/images/avatars/
    - assets/icons/

